### ISSUE TITLE
Scroll no baja del todo

### ISSUE THREAD

**Issue by lufte** [elfoxero/file-manager#16]
En la última versión no es posible "scrollear" hasta abajo de todo, es como si se trancara antes. Estoy en un alcatel otf con firefox os 1.4.

**Comment by elfoxero** [comment]
Gracias por reportarlo, en la última versión de la app el problema debería haberse resuelto, solo he podido testearlo en el simulador, y aunque en la imagen no se ve claramente la barra de desplazamiento, parece bajar completamente.

![captura de pantalla de 2015-01-03 23 48 40](https://cloud.githubusercontent.com/assets/1578078/5604816/a6bb099a-93a3-11e4-89de-9921e484fcb9.png)
