### ISSUE TITLE
Support of OPML MIME type

### ISSUE THREAD

**Issue by ardnould** [elfoxero/file-manager#18]
It can be interesting to support OPML/XML file type:
`text/x-opml, application/xml, text/xml`

OPML is used by RSS/Atom applications.

Thank you.

**Comment by elfoxero** [comment]
Thanks for the suggestion, this feature has been implemented and will be available as soon as be approved.

![captura de pantalla de 2015-01-04 00 52 47](https://cloud.githubusercontent.com/assets/1578078/5604924/524a8f5c-93ad-11e4-8d2b-2b60ca7eb1b8.png)

![captura de pantalla de 2015-01-04 00 52 57](https://cloud.githubusercontent.com/assets/1578078/5604925/576ab570-93ad-11e4-8657-457643d1932c.png)
