### ISSUE TITLE
Folders don't open on touch

### ISSUE THREAD

**Issue by petrica-celrau** [elfoxero/file-manager#22]
Hi, I installed your app on my ZTE Open C with v2.1 and I have a hard time navigating through folders, they don't quite respond to touches. That is, one out of 10 I manage to open a folder. Long touch works ok. More surprising, the app called Files which I got from Marketplace and which seems to be identical, works as expected.

**Comment by petrica-celrau** [comment]
Well, I just installed it from Marketplace and it works fine.... You have any explanation? What's different?

**Comment by elfoxero** [comment]
Sorry for the late response, I think it was because you had an old version of File Manager.
https://github.com/elfoxero/file-manager/commit/00235306753daed4fd544546981940b26c50d3a7
(look at js/files.js)
