### ISSUE TITLE
No Icon on Home Screen

### ISSUE THREAD

**Issue by naitsirch** [elfoxero/file-manager#46]
Today I have installed this app on my ZTE Open C (FirefoxOS 1.3), but there was no icon added to the home screen. It is very uncomfortable to start the app without the icon. How could that happen?

I don't know if this is a bug with *file-manager* or with *Firefox OS* itself. Do you have any idea?

**Comment by j8r** [comment]
I never had this problem on my Firefox OS phone (1.3 then 2.0) and in the Firefox OS simulator (3.0). Try to reinstall it, and try with other applications, this can come from your phone. You can also try to install file-manager directly from the source with your PC, or install a newer version of Firefox OS.

**Comment by naitsirch** [comment]
I realized that this problem does not only exist for file-manager. It was just the first time it happened. Each time I install an app now, leads to this problem :-( so I'll close this issue.
