### ISSUE TITLE
Ukrainian localizationn

### ISSUE THREAD

**Issue by stenox** [elfoxero/file-manager#47]
I'd like to translate File manager into Ukrainian.

**Comment by j8r** [comment]
Nice initiative! I've just created the base of the new Ukrainian localization in the "ukrainian-language" branch :)

**Comment by stenox** [comment]
Great! Thanks!

**Comment by artpoli** [comment]
There were several updates since closing this issue, but localization still not landed.
I'd like to know when it will come.
